project:
  type: website
  output-dir: docs

website:
  title: "Análise do Censo 2022 - Domicílios"
  navbar:
    left:
      - href: index.qmd
        text: Sobre
      - href: 01-import-data.qmd
        text: "Dados"
      - href: 02-indicators.qmd
        text: "Dados"  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual